#!/bin/bash
set -euo pipefail

docker tag "$IMAGE_NAME" "$DOCKER_REPO:$SOURCE_COMMIT"
docker push "$DOCKER_REPO:$SOURCE_COMMIT"

SHORTHASH="$(git rev-parse --short HEAD)"
docker tag "$IMAGE_NAME" "$DOCKER_REPO:$SHORTHASH"
docker push "$DOCKER_REPO:$SHORTHASH"


GO_VERSION="$(grep 'const Version' speedtest_exporter.go | \
    awk 'match($0, /[0-9].[0-9].[0-9]/) {print substr( $0, RSTART, RLENGTH )}')"

TAG_VERSION="$( (git describe --exact-match --tags HEAD || echo "") | tr -d 'v' )"

if [ -z "$TAG_VERSION" ] || [ "$GO_VERSION" != "$TAG_VERSION" ]; then
    echo "Not a tagged version. Skipping version image tags"
    exit 0
fi

GO_VERSION_MINOR=${GO_VERSION%.*}
GO_VERSION_MAJOR=${GO_VERSION_MINOR%.*}

echo "Tagging bugfix version $GO_VERSION"
docker tag "$IMAGE_NAME" "$DOCKER_REPO:${GO_VERSION}"
docker push "$DOCKER_REPO:${GO_VERSION}"

echo "Tagging minor version $GO_VERSION_MINOR"
docker tag "$IMAGE_NAME" "$DOCKER_REPO:${GO_VERSION_MINOR}"
docker push "$DOCKER_REPO:${GO_VERSION_MINOR}"

echo "Tagging major version $GO_VERSION_MAJOR"
docker tag "$IMAGE_NAME" "$DOCKER_REPO:${GO_VERSION_MAJOR}"
docker push "$DOCKER_REPO:${GO_VERSION_MAJOR}"
